const profileData = {
  jp: {
    heroRole: "外国人材サポート × 業務改善（RPA/IT）",
    heroSummary:
      "日本とインドネシアの現場をつなぐサポート経験を活かし、生活・就業支援と業務効率化の両面で価値を提供します。",
    ctaContact: "メールで連絡",
    ctaSkills: "スキルを見る",
    aboutTitle: "私について",
    aboutBody:
      "IKBAL RAMDAN SUHENDARです。温浴施設での接客、外国人スタッフ支援、公的書類対応、日印間コミュニケーション支援に従事してきました。現場課題を理解しながら、Cursor ProやGemini Proを活用した業務改善にも取り組んでいます。現在はUiPathとPythonを継続学習し、現場とITをつなぐ人材として成長中です。",
    skillsTitle: "主なスキル",
    skills: [
      "日印コミュニケーション支援",
      "外国人スタッフ受け入れサポート",
      "公的書類・事務処理",
      "接客・現場オペレーション",
      "Word / Excel / PowerPoint",
      "Cursor Pro / Gemini Pro",
      "Python基礎（学習中）",
      "UiPath基礎（学習中）",
    ],
    experienceTitle: "職務経験",
    experience: [
      {
        period: "2025 - 現在",
        title: "株式会社大協ホールディングス（日帰り温泉オーシャン）",
        body: "外国人スタッフ支援、日印間の調整・通訳、接客現場対応に加え、AIツールを用いた業務効率化に従事。",
      },
      {
        period: "2023 - 2024",
        title: "交野カントリークラブ（インターンシップ）",
        body: "キャディ業務として、お客様へのコース案内・プレーサポートを担当。日本式ホスピタリティを実務で習得。",
      },
      {
        period: "2022",
        title: "株式会社まつの（アルバイト）",
        body: "留学期間中の現場業務に従事し、基礎的な日本語ビジネスコミュニケーションを強化。",
      },
    ],
    educationTitle: "学歴",
    education: [
      "UNIKOM（インドネシアコンピューター大学）日本文学士 卒業（2024）",
      "大阪国際大学 交換留学 修了（2022）",
    ],
    certTitle: "資格",
    certs: ["JLPT N2（2026）", "JLPT N3（2023）"],
    contactTitle: "連絡先",
    contactBody: "お仕事のご相談はメールでご連絡ください。",
    emailLabel: "メール",
    footerText: "Profile site created with HTML, Tailwind CSS, and JavaScript.",
  },
  en: {
    heroRole: "Foreign Staff Support x Process Improvement (RPA/IT)",
    heroSummary:
      "I provide value through both staff support and workflow improvement, based on hands-on experience connecting teams in Japan and Indonesia.",
    ctaContact: "Contact by Email",
    ctaSkills: "View Skills",
    aboutTitle: "About Me",
    aboutBody:
      "I am IKBAL RAMDAN SUHENDAR. I have experience in customer service, foreign staff support, document administration, and JP-ID communication support in Japan. Alongside field operations, I also work on process improvement using AI tools such as Cursor Pro and Gemini Pro. I am currently studying UiPath and Python to bridge operations and IT.",
    skillsTitle: "Core Skills",
    skills: [
      "JP-ID communication support",
      "Foreign staff onboarding support",
      "Administrative document handling",
      "Customer service and field operations",
      "Word / Excel / PowerPoint",
      "Cursor Pro / Gemini Pro",
      "Python fundamentals (learning)",
      "UiPath fundamentals (learning)",
    ],
    experienceTitle: "Experience",
    experience: [
      {
        period: "2025 - Present",
        title: "DaiKyo Holdings (Day Onsen Ocean)",
        body: "Supporting foreign staff, JP-ID coordination and interpretation, customer-facing operations, and AI-assisted process improvement.",
      },
      {
        period: "2023 - 2024",
        title: "Katano Country Club (Internship)",
        body: "Worked as a caddy, guiding customers and supporting gameplay while learning Japanese hospitality standards.",
      },
      {
        period: "2022",
        title: "Matsuno Co., Ltd. (Part-time)",
        body: "Handled practical field tasks during exchange study and strengthened Japanese business communication basics.",
      },
    ],
    educationTitle: "Education",
    education: [
      "UNIKOM (Indonesia Computer University), BA in Japanese Literature (2024)",
      "Osaka International University, Exchange Program (2022)",
    ],
    certTitle: "Certifications",
    certs: ["JLPT N2 (2026)", "JLPT N3 (2023)"],
    contactTitle: "Contact",
    contactBody: "Please contact me by email for job opportunities or collaboration.",
    emailLabel: "Email",
    footerText: "Profile site created with HTML, Tailwind CSS, and JavaScript.",
  },
  id: {
    heroRole: "Dukungan Staf Asing x Peningkatan Proses (RPA/IT)",
    heroSummary:
      "Saya membantu operasional dan pengembangan proses kerja melalui pengalaman langsung menjembatani tim Jepang dan Indonesia.",
    ctaContact: "Hubungi via Email",
    ctaSkills: "Lihat Keahlian",
    aboutTitle: "Tentang Saya",
    aboutBody:
      "Saya IKBAL RAMDAN SUHENDAR. Saya memiliki pengalaman dalam layanan pelanggan, pendampingan staf asing, administrasi dokumen, serta dukungan komunikasi Jepang-Indonesia. Selain mendukung operasional lapangan, saya juga aktif meningkatkan efisiensi kerja menggunakan AI tools seperti Cursor Pro dan Gemini Pro. Saat ini saya mempelajari UiPath dan Python untuk memperkuat jalur karier hybrid operasional dan IT.",
    skillsTitle: "Keahlian Utama",
    skills: [
      "Dukungan komunikasi JP-ID",
      "Pendampingan staf asing",
      "Administrasi dokumen",
      "Layanan pelanggan dan operasional",
      "Word / Excel / PowerPoint",
      "Cursor Pro / Gemini Pro",
      "Dasar Python (belajar)",
      "Dasar UiPath (belajar)",
    ],
    experienceTitle: "Pengalaman",
    experience: [
      {
        period: "2025 - Sekarang",
        title: "DaiKyo Holdings (Day Onsen Ocean)",
        body: "Menangani dukungan staf asing, koordinasi JP-ID, bantuan komunikasi, operasional layanan, dan inisiatif efisiensi dengan AI.",
      },
      {
        period: "2023 - 2024",
        title: "Katano Country Club (Magang)",
        body: "Bertugas sebagai caddy: memandu pelanggan di lapangan dan mendukung permainan sambil mempelajari standar hospitality Jepang.",
      },
      {
        period: "2022",
        title: "Matsuno Co., Ltd. (Part-time)",
        body: "Menjalankan tugas lapangan saat masa pertukaran pelajar dan memperkuat dasar komunikasi bisnis Jepang.",
      },
    ],
    educationTitle: "Pendidikan",
    education: [
      "UNIKOM (Universitas Komputer Indonesia), S1 Sastra Jepang (2024)",
      "Osaka International University, Program Pertukaran (2022)",
    ],
    certTitle: "Sertifikasi",
    certs: ["JLPT N2 (2026)", "JLPT N3 (2023)"],
    contactTitle: "Kontak",
    contactBody: "Untuk peluang kerja atau kolaborasi, silakan hubungi saya lewat email.",
    emailLabel: "Email",
    footerText: "Situs profil dibuat dengan HTML, Tailwind CSS, dan JavaScript.",
  },
};
